/**
 * This is the abstract configuration for  Ginger you can overwrite it by AssinINg a config to yur engine
 */
module.exports={
	//Components configurations
	'components':{
		'express':{
			'port':3000,
			'host':'0.0.0.0'
		},
		'socketio':{
			'port':3040
		},
		'db':{
			'mongo':{
				'uri':'mongodb://localhost/ginger'
			}
		},
		'session':{
			'secret':'Change_this!'
		},
		'log':{}
	},
	'gateways':{
		'HTTP':{},
		'JSONRpc':{'prefix':'JSONRPC'},
		'SocketIO':{}
	},
	'errors':[
		'NotFound',
		'Validate',
		'InvalidParams',
		'InvalidRequest',
		'InternalError'
	],
	'gatewayDir':__dirname+'/../gateway/',
	'componentDir':__dirname+'/../components/',
	'bootstrapDir':__dirname+'/../bootstraps/',
	'abstractGatewayPath':__dirname+'/../gateway/AbstractGateway.js',
	'abstractModelPath':__dirname+'/../mvc/AbstractModel.js',
	'abstractControllerPath':__dirname+'/../mvc/AbstractController.js',
	'bootstrapPath':__dirname+'/../Bootstrap.js'
};