/**
 * This is the abstract configuration for  Ginger you can overwrite it by AssinINg a config to yur engine
 */
module.exports={
	//Components configurations
	'components':{
		'Express':{
			'port':3000,
			'host':'0.0.0.0',
			'startOrder':'beforeGateways'
		},
		'SocketIO':{
			'port':3040
		},
		'DataBase':{
			'mongo':{
				//'uri':'mongodb://localhost:27017/gingerTests'
				'url':'mongodb://localhost',
				'port':'27017',
				'base':'ginger'
			}
		},
		'Authentication':{
			'model':'authentication'
		},
		'Session':{
			'secret':'Change_this!',
			'saveUninitialized':true,
			'resave':true
		},
		'Log':{}
	},
	'gateways':{
		'HTTP':{
			'components':['Express','Session','Authentication','DataBase']
		},
		'JSONRPC':{
			'prefix':'JSONRPC',
			'components':['Express','Session','Authentication','DataBase']
		},
		'SocketIO':{}
	},
	'errors':[
		'NotFound',
		'Validate',
		'InvalidParams',
		'InvalidRequest',
		'InternalError'
	]
};